#!/bin/sh

# Source tutorial clean functions
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"

#The following will also remove the system/blockMeshDict file because we 
#have system/blockMeshDict.m4. (See the definiton of "cleanCase" function
#in $WM_PROJECT_DIR/bin/tools/CleanFunctions.
cleanCase
